//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZavršniRad_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik
    {
        public int Id { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Email { get; set; }
        public string Mobitel { get; set; }
        public string Adresa { get; set; }
        public string KorisnickoIme { get; set; }
        public string Lozinka { get; set; }
        public bool IsAdmin { get; set; }
        public bool Aktivan { get; set; }
        public string LozinkaHash { get; set; }
        public string LozinkaSalt { get; set; }
    
        public virtual Osoblje Osoblje { get; set; }
        public virtual Pacijent Pacijent { get; set; }
        public virtual Stomatolog Stomatolog { get; set; }
    }
}
