//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZavršniRad_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocjena
    {
        public int Id { get; set; }
        public System.DateTime DatumOcjenjivanja { get; set; }
        public int OcjenaInt { get; set; }
        public int UslugaId { get; set; }
        public int PacijentId { get; set; }
    
        public virtual Pacijent Pacijent { get; set; }
        public virtual Usluga Usluga { get; set; }
    }
}
