//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZavršniRad_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poruka
    {
        public int Id { get; set; }
        public int PacijentId { get; set; }
        public int StomatologId { get; set; }
        public int From { get; set; }
        public Nullable<int> To { get; set; }
        public string TekstPoruke { get; set; }
        public System.DateTime Datum { get; set; }
        public bool Procitana { get; set; }
    
        public virtual Pacijent Pacijent { get; set; }
        public virtual Stomatolog Stomatolog { get; set; }
    }
}
