//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZavršniRad_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racun
    {
        public int Id { get; set; }
        public bool Uplaćeno { get; set; }
        public decimal Cijena { get; set; }
        public System.DateTime Datum { get; set; }
        public Nullable<int> OsobljeId { get; set; }
        public Nullable<int> PacijentId { get; set; }
        public Nullable<int> PregledId { get; set; }
    
        public virtual Osoblje Osoblje { get; set; }
        public virtual Pacijent Pacijent { get; set; }
        public virtual Pregled Pregled { get; set; }
    }
}
