//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZavršniRad_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zub
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zub()
        {
            this.IzvrsenaUslugas = new HashSet<IzvrsenaUsluga>();
            this.UspostavljenaDijagnozas = new HashSet<UspostavljenaDijagnoza>();
        }
    
        public int Id { get; set; }
        public int BrojZuba { get; set; }
        public string NazivZuba { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzvrsenaUsluga> IzvrsenaUslugas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UspostavljenaDijagnoza> UspostavljenaDijagnozas { get; set; }
    }
}
